### ISSUE TITLE
Create docs about working in Inkscape

### ISSUE THREAD

**Issue by RikeVoltz** [Raw-Machine-Games/vile-four#4]
Create the quick guide (some short synopsis) of working in Inkscape (basic operations, primitives, grouping, ungrouping, etc.). It will help other people start working in Inkscape pretty much faster, than if they explored it themselves.

**Comment by RikeVoltz** [comment]
Free form, add pages to GitHub wiki

**Comment by youpifun** [comment]
https://drive.google.com/open?id=1XhPeIo0DI2U_aDagL642eoRaEZT4QRp9
