### ISSUE TITLE
Game prototype discussion

### ISSUE THREAD

**Issue by RikeVoltz** [Raw-Machine-Games/vile-four#5]
In this issue we need to document our expectations about design and tech features of alpha version of the game.
You can express your thoughts in free form, but it’s advisable to break your expectations by topics - i.e. _gameplay_, _design_, _setting_, _mechanics_, _features_ etc.

**Comment by HappyVVlnaJIe** [comment]
Механика - движение, т.е. ходьба, прыжки, атака (обычная), смерть моба
Геймплей - мобы, гг

**Comment by youpifun** [comment]
Механика: движение в стороны, прыжок. Одна атака. Из врагов пару тестовых мобов.

**Comment by ShumilinPavel** [comment]
В боевку можно было бы добавить увороты.

**Comment by RikeVoltz** [comment]
Итог:
Движок: анимация движения, приседания, прыжка, взаимодействие с мобами, убийство моба, возможность коопа, три разных оружия с разными механиками, комбинации движений (прыжок+удар, прыжок+движение, etc.), босс
Графика: модели персонажей, модели 3 мобов, текстуры окружающей среды (земли, неба, стен (если будут), деревьев, и т. д.), модели 3 оружий, модель босса
Звук - первичные звуки персонажей, мобов и босса.
MVP длится до 20 декабря 2019 - 41-44 недели - однонедельные спринты. 45-52 - двухнедельные. Итого: 4 однонедельных+4двухнедельных = 8 спринтов.

**Comment by HappyVVlnaJIe** [comment]
Движение, стрельба, прыжок
